@echo off
echo Configuring Git...
"C:\Program Files\Git\bin\git.exe" config --global user.name "Heath Ruddick"
"C:\Program Files\Git\bin\git.exe" config --global user.email "your-email@example.com"
echo Initializing Git repository...
"C:\Program Files\Git\bin\git.exe" init
echo Adding files to Git repository...
"C:\Program Files\Git\bin\git.exe" add index.html main.js README.md favicon.ico .gitignore
echo Committing files...
"C:\Program Files\Git\bin\git.exe" commit -m "Initial commit"
echo Adding remote repository...
"C:\Program Files\Git\bin\git.exe" remote add origin https://github.com/Heath-Ruddick/Vibe-code-test.git
echo Pushing to GitHub...
"C:\Program Files\Git\bin\git.exe" push -u origin master
echo Done!
pause 